import type {IconName} from '../components/common/IconSymbol';
import {Colors} from '../theme';

export type ShowcaseStatus = 'ready' | 'lab' | 'parked';

type ShowcaseRegistryEntry = {
  routeKey: string;
  title: string;
  headerTitle?: string;
  subtitle: string;
  icon: IconName;
  color: string;
  demoCount: number;
  deepLinkSlug: string;
  status: ShowcaseStatus;
  isNew?: boolean;
};

export const showcaseRegistry = [
  {
    routeKey: 'Layouts',
    title: 'Layouts',
    subtitle: 'Flexbox, responsive grid, masonry & safe area',
    icon: 'layout',
    color: Colors.success,
    demoCount: 6,
    deepLinkSlug: 'layouts',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Lists',
    title: 'Lists & Scroll',
    headerTitle: 'Lists & Scroll',
    subtitle: 'FlatList, sticky sections, snap, parallax & refresh',
    icon: 'list',
    color: Colors.primary,
    demoCount: 10,
    deepLinkSlug: 'lists',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Navigation',
    title: 'Navigation',
    headerTitle: 'Advanced Navigation',
    subtitle: 'Swipe tabs, drawer, sheet routes & dots',
    icon: 'navigation',
    color: Colors.accent,
    demoCount: 6,
    deepLinkSlug: 'navigation',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Animations',
    title: 'Animations',
    subtitle: 'Spring, bounce, fade, shimmer & interactive',
    icon: 'spark',
    color: Colors.secondary,
    demoCount: 15,
    deepLinkSlug: 'animations',
    status: 'ready',
  },
  {
    routeKey: 'Canvas',
    title: 'Canvas 2D',
    subtitle: 'Drawing, text, shapes, export & snap grid',
    icon: 'canvas',
    color: Colors.orange,
    demoCount: 10,
    deepLinkSlug: 'canvas',
    status: 'ready',
  },
  {
    routeKey: 'ThreeD',
    title: '3D Transforms',
    subtitle: 'OBJ parser, sphere shading, lighting & shader surface',
    icon: 'cube',
    color: Colors.accent,
    demoCount: 7,
    deepLinkSlug: '3d',
    status: 'ready',
  },
  {
    routeKey: 'Charts',
    title: 'Charts & Data',
    headerTitle: 'Charts & Data',
    subtitle: 'Realtime analytics, treemap, funnel, radar & finance views',
    icon: 'chart',
    color: Colors.warning,
    demoCount: 17,
    deepLinkSlug: 'charts',
    status: 'ready',
  },
  {
    routeKey: 'Svg',
    title: 'SVG & Vector',
    headerTitle: 'SVG & Vector',
    subtitle: 'Morphing, path draw, animated icons & pure SVG charts',
    icon: 'vector',
    color: Colors.primary,
    demoCount: 6,
    deepLinkSlug: 'svg',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'DataGrid',
    title: 'DataGrid',
    headerTitle: 'DataGrid Studio',
    subtitle: 'Frozen columns, filters, edit, export & 10k-row virtualization',
    icon: 'table',
    color: Colors.success,
    demoCount: 26,
    deepLinkSlug: 'datagrid',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Media',
    title: 'Camera & Photos',
    headerTitle: 'Camera & Photos',
    subtitle: 'Live preview, capture, gallery, zoom, crop and filters',
    icon: 'camera',
    color: Colors.orange,
    demoCount: 10,
    deepLinkSlug: 'media',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Audio',
    title: 'Audio',
    headerTitle: 'Audio Studio',
    subtitle: 'Record, visualize waveform, play, seek and manage clips',
    icon: 'audio',
    color: Colors.secondary,
    demoCount: 6,
    deepLinkSlug: 'audio',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Video',
    title: 'Video',
    headerTitle: 'Video Studio',
    subtitle: 'Player controls, seek, fullscreen, PiP and generated thumbnails',
    icon: 'video',
    color: Colors.primary,
    demoCount: 5,
    deepLinkSlug: 'video',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Files',
    title: 'Files & Documents',
    headerTitle: 'Files & Documents',
    subtitle: 'Picker, PDF reader, search, cache, share and image previews',
    icon: 'file',
    color: Colors.warning,
    demoCount: 10,
    deepLinkSlug: 'files',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Platform',
    title: 'Device & System',
    headerTitle: 'Device & System',
    subtitle: 'Sensors, Material You, shortcuts, PiP, channels and runtime APIs',
    icon: 'device',
    color: Colors.warning,
    demoCount: 38,
    deepLinkSlug: 'platform',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Web',
    title: 'WebView & Browser',
    headerTitle: 'WebView & Browser',
    subtitle: 'Custom URLs, bridge messaging, JS injection and special link handling',
    icon: 'browser',
    color: Colors.primary,
    demoCount: 7,
    deepLinkSlug: 'web',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Network',
    title: 'Networking & APIs',
    headerTitle: 'Networking & APIs',
    subtitle: 'REST, GraphQL, WebSocket, cache, retries and transfer progress',
    icon: 'network',
    color: Colors.success,
    demoCount: 10,
    deepLinkSlug: 'network',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Storage',
    title: 'Local Storage',
    headerTitle: 'Local Storage',
    subtitle: 'AsyncStorage, SQLite-style data, MMKV-style hot store, vault and cache',
    icon: 'storage',
    color: Colors.accent,
    demoCount: 5,
    deepLinkSlug: 'storage',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Maps',
    title: 'Maps & Geospatial',
    headerTitle: 'Maps & Geospatial',
    subtitle: 'Interactive map, route, geofence, geocoding, clustering and styles',
    icon: 'map',
    color: Colors.success,
    demoCount: 8,
    deepLinkSlug: 'maps',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Auth',
    title: 'Auth Demo',
    headerTitle: 'Auth Demo',
    subtitle: 'Login, signup, biometrics, PIN lock, social providers and 2FA',
    icon: 'lock',
    color: Colors.secondary,
    demoCount: 7,
    deepLinkSlug: 'auth',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Themes',
    title: 'Themes & Appearance',
    headerTitle: 'Themes & Appearance',
    subtitle: 'Dark, light, system sync, custom palettes, font scale and contrast',
    icon: 'theme',
    color: Colors.primary,
    demoCount: 8,
    deepLinkSlug: 'themes',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Codes',
    title: 'QR & Barcode',
    headerTitle: 'QR & Barcode',
    subtitle: 'Camera-style scanning, QR generation, barcode formats and history',
    icon: 'code',
    color: Colors.warning,
    demoCount: 5,
    deepLinkSlug: 'codes',
    status: 'lab',
    isNew: true,
  },
  {
    routeKey: 'Utilities',
    title: 'Advanced Utilities',
    headerTitle: 'Advanced Utilities',
    subtitle: 'Calendar, drag-and-drop, markdown, timers, flows and dashboard demos',
    icon: 'tools',
    color: Colors.success,
    demoCount: 20,
    deepLinkSlug: 'utilities',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Particles',
    title: 'Particles',
    subtitle: 'Floating neon particle system',
    icon: 'particles',
    color: Colors.orange,
    demoCount: 1,
    deepLinkSlug: 'particles',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Colors',
    title: 'Color Picker',
    headerTitle: 'Color Picker',
    subtitle: 'HSL palette with 120+ swatches',
    icon: 'palette',
    color: Colors.pink,
    demoCount: 1,
    deepLinkSlug: 'colors',
    status: 'ready',
    isNew: true,
  },
  {
    routeKey: 'Reanimated',
    title: 'Reanimated',
    headerTitle: 'Reanimated Worklets',
    subtitle: 'Worklets, shared values & UI thread animations',
    icon: 'bolt',
    color: Colors.warning,
    demoCount: 7,
    deepLinkSlug: 'reanimated',
    status: 'ready',
    isNew: true,
  },
] as const satisfies readonly ShowcaseRegistryEntry[];

export type ShowcaseScreenMeta = (typeof showcaseRegistry)[number];
export type ShowcaseRouteKey = ShowcaseScreenMeta['routeKey'];

export const showcaseLinkingScreens = Object.fromEntries(
  showcaseRegistry.map(screen => [screen.routeKey, screen.deepLinkSlug]),
) as Record<ShowcaseRouteKey, ShowcaseScreenMeta['deepLinkSlug']>;
